name: Deploy Laravel to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove non-deploy folders
        run: | 
            rm -rf .github .git node_modules tests vendor
            rm -rf storage bootstrap/cache
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pdo, pdo_mysql, curl, xml, json
          coverage: none
        
      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "."
          target: "/var/www/html/backend.cabifyit.com"
          strip_components: 1
          overwrite: true

      - name: Run SSH commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/html/backend.cabifyit.com
            # Ensure required folders exist
            mkdir -p storage bootstrap/cache

            # Correct ownership (adjust user if not www-data)
            sudo chown -R www-data:www-data storage bootstrap/cache

            # Correct permissions
            sudo chmod -R 775 storage bootstrap/cache public

            composer install --no-dev --optimize-autoloader --prefer-dist
            php artisan migrate
            php artisan tenants:migrate --path=database/migrations/tenant
            php artisan db:seed
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize:clear
            cd socket-server
            npm install
            pm2 restart project-socket || pm2 start index.js --name project-socket
            sudo systemctl reload nginx